### ISSUE TITLE
class keyword breaks highlighting

### ISSUE THREAD

**Issue by dkl** [sorucoder/freebasic-vscode-extension#1]
Hi!

Today I noticed this new FreeBASIC syntax coloring extension for VSCode, and gave it a try. There seems to be an issue related to the `class` keyword:

First the example code:
```
type UDT
	class as integer
end type
dim p as UDT ptr = new UDT
if p->class = 1 then
	print "yes"
end if
```
And this is what VSCode makes of it:
![image](https://user-images.githubusercontent.com/212549/198698679-d8e5bf32-d117-4770-881d-dd30354f8ceb.png)

FreeBASIC has some oddities, one of them is that you can use keywords as names of fields (structure members) at least in some cases, so maybe this is related to that. Although, I tried with other keywords such as `type`, which is also allowed by fbc as field name, but there it didn't happen:
![image](https://user-images.githubusercontent.com/212549/198699031-42d96aaf-3354-4286-8b5a-4a729795478b.png)

**Comment by sorucoder** [comment]
So the reason behind the `class` keyword breaking highlighting is because I have an implemented a bare-bones highlighting for it, as FreeBASIC states on their documentation that the keyword is reserved, but is not implemented yet. The syntax I implemented is just a `class ... end class` block. However, the `type` declaration is actually flawed too. It looks for an identifier after `type`, both for type aliases and type declarations. I do have a fix in mind, and I'll make the change as soon as I can.

**Comment by sorucoder** [comment]
It should be fixed now.
